version: 2
updates:
- package-ecosystem: mix
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: cors_plug
    versions:
    - 2.0.2
  - dependency-name: plug_cowboy
    versions:
    - 2.4.1
